"""Loads product catalog data from data/products.json.

The catalog file is produced by a separate/parallel process. Documented
schema per product record:

    {
        "id": int,
        "title": str,
        "description": str,
        "category": str,
        "price": float
    }

If the file is not present yet, `load_products` raises a clear
FileNotFoundError rather than failing silently, so callers (e.g. app
startup) can decide how to handle a missing catalog.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.models import Product

# Repo layout: <repo_root>/backend/app/data_loader.py -> <repo_root>/data/products.json
DATA_FILE = Path(__file__).resolve().parents[2] / "data" / "products.json"


def load_products(path: Path | str = DATA_FILE) -> list[Product]:
    """Load and validate the product catalog from a JSON file.

    Args:
        path: Path to the products.json file. Defaults to
            <repo_root>/data/products.json.

    Returns:
        A list of validated Product models.

    Raises:
        FileNotFoundError: If the catalog file does not exist yet.
        ValueError: If the file content is not a JSON list or fails
            Product validation.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Product catalog not found at {path}. It may still be being "
            "generated by a parallel process — try again once it exists."
        )

    with path.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    if not isinstance(raw, list):
        raise ValueError(
            f"Expected {path} to contain a JSON list of product records, "
            f"got {type(raw).__name__}."
        )

    return [Product.model_validate(item) for item in raw]


def product_text(product: Product) -> str:
    """Build the text blob used for both BM25 tokenization and embeddings."""
    return f"{product.title} {product.description} {product.category}"
